services:
  - type: web
    name: lucidspeakai-backend
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: bash render-build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
